# All containers are accessible via localhost:
services:
  auth-server:
    image: auth-server:latest
    build: ./auth-server
    container_name: auth-server
    ports: # All container ports are defined here:
      - "9000:9000"
      - "8090:8090"
      - "8080:8080"
    healthcheck:
      test: curl --fail http://localhost:9000/actuator/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  resource-server:
    image: resource-server:latest
    build: ./resource-server
    container_name: resource-server
    network_mode: "service:auth-server" # No port is defined and this container is attached to auth-server network as localhost.
    depends_on:
      auth-server:
        condition: service_healthy

  client:
    image: client:latest
    build: ./client
    container_name: client
    network_mode: "service:auth-server" # No port is defined and this container is attached to auth-server network as localhost.
    depends_on:
      auth-server:
        condition: service_healthy
